EXNS: include/linux: compiler.h/compiler_types.h split and rework
 - In Mainline Linux compiler.h has been split (amongst many other changes).
   Some of the changes I can't easily integrate, however ~ I still need to do
   the split (and eventuall kill lockless_dereference), as some pressing RCU
   changes require said changes...

 - first, update a few bits using these commits;

 1. sparse: Add __private to privatize members of structs compiler.h: add
    support for malloc attribute
 2. tracing: Process constants for (un)likely() profiler
 3. tracing: Show number of constants profiled in likely profiler
 4. locking/barriers: Add implicit smp_read_barrier_depends() to READ_ONCE()

 NOTE: there are lots of commits pertaining the gcc-plugins that I don't
       support. therefore I have skipped over them (for now).

 - Next, manually split the code (because I have to), based on this commit;

 5. linux/compiler.h: Split into compiler.h and compiler_types.h

 - at this point, gcc complains;

In file included from ./arch/arm64/include/asm/opcodes.h:1,
                 from ./arch/arm64/include/asm/sysreg.h:25,
                 from ./arch/arm64/include/asm/cpufeature.h:13,
                 from ./arch/arm64/include/asm/alternative.h:4,
                 from ./arch/arm64/include/asm/uaccess.h:21,
                 from fs/proc/root.c:9:
./arch/arm64/include/../../arm/include/asm/opcodes.h:14:52: error: unknown type name ‘u32’
 extern asmlinkage unsigned int arm_check_condition(u32 opcode, u32 psr);
                                                    ^~~
./arch/arm64/include/../../arm/include/asm/opcodes.h:14:64: error: unknown type name ‘u32’
 extern asmlinkage unsigned int arm_check_condition(u32 opcode, u32 psr);

  - the quick-fix is to add;

 --- a/arch/arm/include/asm/opcodes.h
 +++ b/arch/arm/include/asm/opcodes.h
 @@ -11,6 +11,7 @@

 #ifndef __ASSEMBLY__
 #include <linux/linkage.h>
 +#include <linux/types.h>
 extern asmlinkage unsigned int arm_check_condition(u32 opcode, u32 psr);
 #endif

 NOTE: I will have to revisit this, but for now this does fix compilation.

Signed-off-by: jordan Johnston <johnstonljordan@gmail.com>